// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	biz2 "helloworld/app/user/internal/biz"
	"helloworld/app/user/internal/conf"
	data2 "helloworld/app/user/internal/data"
	server2 "helloworld/app/user/internal/server"
	service2 "helloworld/app/user/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {

	dataData, cleanup, err := data2.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data2.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz2.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service2.NewGreeterService(greeterUsecase)

	userRepo := data2.NewUserRepo(dataData, logger)
	userUsecase := biz2.NewUserUsecase(userRepo, logger)
	userService := service2.NewUserService(userUsecase)

	httpServer := server2.NewHTTPServer(confServer, greeterService, userService, logger)
	grpcServer := server2.NewGRPCServer(confServer, greeterService, userService, logger)

	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
